[pytest]
cache_dir = .tmp/.pytest_cache
markers =
    slow: marks tests as slow (deselect with -m "not slow" or --ignore for integration)
filterwarnings =
    ignore::pytest.PytestReturnNotNoneWarning
    ignore::pytest.PytestCollectionWarning
    ignore::DeprecationWarning:datetime.*
    ignore:Thread leak between test modules:UserWarning

